# Generated by Django 3.1.4 on 2021-01-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='noofposition',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
