# Generated by Django 3.1.5 on 2021-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=60)),
                ('noofposition', models.IntegerField()),
                ('skill', models.CharField(max_length=70)),
                ('duration', models.TextField(max_length=17)),
            ],
        ),
    ]
